"""Utility to refresh harness-lab CI baseline file from current performance."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from app.harness.engine import HarnessEngine

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = ROOT / "data" / "harness_lab_ci_baseline.json"


def _parse_presets(raw: str) -> list[str]:
    parts = [item.strip().lower() for item in raw.split(",") if item.strip()]
    return parts or ["core", "daily", "research", "strict"]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate harness-lab CI baseline file.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Baseline output JSON path")
    parser.add_argument("--presets", default="core,daily,research,strict", help="Comma-separated presets")
    parser.add_argument("--repeats", type=int, default=1, help="Repeat count per scenario")
    parser.add_argument("--seed", type=int, default=7, help="Seed used by bootstrap CI")
    parser.add_argument(
        "--composite-floor-margin",
        type=float,
        default=0.09,
        help="Margin subtracted from current best composite for min_best_composite",
    )
    parser.add_argument(
        "--value-floor-margin",
        type=float,
        default=5.0,
        help="Margin subtracted from current avg value index for min_avg_value_index",
    )
    args = parser.parse_args(argv)

    engine = HarnessEngine()
    presets = _parse_presets(args.presets)
    config: dict[str, Any] = {
        "version": "auto-generated",
        "note": "Generated by app.harness.ci_baseline",
        "global": {
            "min_release_decision": "caution",
            "max_abs_composite_drop": 0.08,
            "max_rel_composite_drop": 0.1,
            "min_category_coverage": 4,
            "min_worst_category_score": 0.62,
        },
        "presets": {},
    }

    for preset in presets:
        payload = engine.run_research_lab(
            preset=preset,
            repeats=max(1, args.repeats),
            seed=args.seed,
            isolate_memory=True,
            fresh_memory_per_candidate=True,
        )
        best = dict(payload.get("best", {}))
        best_composite = float(best.get("composite_score", 0.0))
        best_value = float(best.get("avg_value_index", 0.0))
        best_safety = float(best.get("avg_security_alignment", 0.0))
        config["presets"][preset] = {
            "baseline_best_composite": round(best_composite, 4),
            "min_best_composite": round(max(0.0, best_composite - args.composite_floor_margin), 4),
            "min_pass_rate": 0.7,
            "min_avg_security_alignment": round(max(0.75, best_safety - 0.1), 4),
            "min_avg_value_index": round(max(60.0, best_value - args.value_floor_margin), 3),
            "min_pareto_frontier_size": 1,
            "min_release_decision": "go",
        }

    path = Path(args.output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(config, indent=2, default=str), encoding="utf-8")
    print(f"baseline written: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
